// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataAccess.UserMigrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20171116172339_UserMigration0001")]
    partial class UserMigration0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Data.County", b =>
                {
                    b.Property<int>("countyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .HasMaxLength(50);

                    b.HasKey("countyId");

                    b.ToTable("lkpCounties");
                });

            modelBuilder.Entity("Models.Data.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("countyId");

                    b.Property<DateTime>("dateAdded");

                    b.Property<DateTime>("dateUpdated");

                    b.Property<string>("email")
                        .HasMaxLength(100);

                    b.Property<string>("firstName")
                        .HasMaxLength(50);

                    b.Property<string>("lastName")
                        .HasMaxLength(50);

                    b.Property<string>("password")
                        .HasMaxLength(100);

                    b.HasKey("userId");

                    b.ToTable("tblUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
